### ISSUE TITLE
Excluding from App Store builds with SPM

### ISSUE THREAD

**Issue by daveverwer** [shinydevelopment/SimulatorStatusMagic#102]
I don't know whether any of you saw [this article from Toomas Vahter](https://augmentedcode.io/2022/05/02/linking-a-swift-package-only-in-debug-builds/) recently? 

I wondered if it might solve the problem of SimulatorStatusMagic and release/App Store builds? It seems like it might. I'm opening this as an issue because it might make a good addition to the README file if it does indeed solve the problem.

**Comment by chrisvasselli** [comment]
Thanks, I didn't see that. I'll give it a shot and see how it works. 👍

**Comment by chrisvasselli** [comment]
After looking at it, my initial reaction is to not add this to the README as an approach for disabling SimulatorStatusMagic. I think we could get this approach working, but it has some drawbacks. For one, it would break the ability for people to choose to link SimulatorStatusMagic in any build that doesn't define `DEBUG`, which could break existing users integrating via Cocoapods/Carthage. And since it requires using a wildcard to exclude certain files from the build based on path, it feels more complicated to setup and a little more error-prone.

I'd tend to leave the current approach of linking to the UI target as the recommended way of integrating via SPM.

@nrbrook any thoughts?

**Comment by nrbrook** [comment]
@chrisvasselli by ui target do you mean UI test target? I would agree that should be the suggested approach.

**Comment by chrisvasselli** [comment]
@nrbrook Yes, sorry I mean the UI test target. Sounds like we're on the same page.

@daveverwer thanks for sharing this! I'm going to close out this issue.

**Comment by daveverwer** [comment]
No problem! Thanks for taking a look!
