### ISSUE TITLE
Location icon

### ISSUE THREAD

**Issue by xkittyqueenx** [shinydevelopment/SimulatorStatusMagic#120]
Is it possible to add a location icon to the status bar? I tried adding it myself but I'm doing something wrong.

Thanks!

**Comment by clindsay3** [comment]
Hey @urlocaluwu! Adding the location icon to the status bar isn't in the scope of this project, since it is focused specifically on reproducing the screenshot conditions used by Apple in their screenshots. That said, if you take a look at SDStatusBarOverriderPost17_0.m (and equivalents for earlier versions of iOS), you could try setting up an override of the `LocationStatusBarItem` status bar item following the pattern you see used for other overrides. I haven't tried it myself, so I can't guarantee it'll work, but it may be worth a shot!
